<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title></title>';
echo '</head>';
echo '<body bgcolor="gray">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<style>';
echo 'body, html {';
echo 'height: 100%;';
echo 'font-family: Arial, Helvetica, sans-serif;';
echo '}';
echo '';
echo '* {';
echo 'box-sizing: border-box;';
echo '}';
echo '';
echo '.bg-img {';
echo '/* The image used */';
echo 'background-image: url("background.jpg");';
echo '';
echo 'min-height: 700px;';
echo '';
echo '/* Center and scale the image nicely */';
echo 'background-position: center;';
echo 'background-repeat: no-repeat;';
echo 'background-size: cover;';
echo 'position: relative;';
echo '}';
echo '';
echo '/* Add styles to the form container */';
echo '.container {';
echo 'position: relative;';
echo 'right: -90;';
echo 'margin: 20px;';
echo 'max-width: 400px;';
echo 'padding: 16px;';
echo 'background-color: white;';
echo 'opacity: 0.8;';
echo '}';
echo '';
echo '/* Full-width input fields */';
echo 'input[type=text], input[type=password] {';
echo 'width: 102%;';
echo 'padding: 15px;';
echo 'margin: 5px 0 22px 0;';
echo 'border: none;';
echo 'background:  #f1f1f1;';
echo '}';
echo '';
echo 'input[type=text]:focus, input[type=password]:focus {';
echo 'background-color: #ddd;';
echo 'outline: none;';
echo '}';
echo '';
echo '/* Set a style for the submit button */';
echo '.btn {';
echo 'background-color: #04AA6D;';
echo 'color: white;';
echo 'padding: 16px 20px;';
echo 'border: none;';
echo 'cursor: pointer;';
echo 'width: 100%;';
echo 'opacity: 0.9;';
echo '}';
echo '';
echo '.btn:hover {';
echo 'opacity: 1;';
echo '}';
echo '</style>';
echo '';
echo '';
echo '<div class="bg-img">';
echo '<form action="connect.php" method="post" class="container">';
echo '<h1>User Form</h1><label for="fname"><b>Name:</b></label> <input type="text" placeholder="Enter name" id="fname" name="fname" required=""><br>';
echo '<br>';
echo '<label for="email">Email:</label> <input type="email" placeholder="Enter email" id="email" name="email" required=""><br></br><label for="password">Enter password:</label> <input type="password" placeholder="Password" id="password" name="password" required=""> <input type="password" placeholder="Confirm Password" id="confirm_password" name="confirm_password" required="">';
echo '<label for="branch"><b>Branch</b></label><br>';
echo '&nbsp; <input type="radio" id="branch" name="branch" value="Computer" required="required"> &nbsp; <label for="html">Computer</label><br>';
echo '&nbsp; <input type="radio" id="branch" name="branch" value="Electrical"> &nbsp; <label for="css">Electrical</label><br>';
echo '&nbsp; <input type="radio" id="branch" name="branch" value="Machanical"> &nbsp; <label for="javascript">Machanical</label><br>';
echo '<br>';
echo '<p>Role:</p>&nbsp; <input type="radio" id="role" name="role" value="Admin" required="required"/> &nbsp; <label for="html">Admin</label><br>';
echo '&nbsp; <input type="radio" id="role" name="role" value="Guest" checked="checked" /> &nbsp; <label for="css">Guest</label><br>';
echo '<br>';
echo '<button type="submit" class="btn">Submit</button>';
echo '</form><br>';
echo '<br> <script>';
echo 'var password = document.getElementById("password");';
echo 'var confirm_password = document.getElementById("confirm_password");';
echo '';
echo 'function validatePassword(){';
echo 'if(password.value != confirm_password.value) {';
echo 'confirm_password.setCustomValidity("Passwords Does not Match");';
echo '} else {';
echo 'confirm_password.setCustomValidity(';');';
echo '}';
echo '}';
echo 'confirm_password.setCustomValidity(';');';
echo 'password.onchange = validatePassword;';
echo 'confirm_password.onkeyup = validatePassword;';
echo '</script>';
echo '</div>-';
echo '</body>';
echo '</html>';
?>